<?php


// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../libs/autoload.php';

$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(__DIR__ . '/../log');
// Specify folder for cache
$configurator->setTempDirectory(__DIR__ . '/../temp');

// Enable RobotLoader - this will load all classes automatically
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../libs')
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$configurator->addConfig(__DIR__ . '/config/config.local.neon', $configurator::NONE); // none section
$container = $configurator->createContainer();

require_once __DIR__ . '/../adds/google/Google_Client.php';
require_once __DIR__ . '/../adds/google/contrib/Google_CalendarService.php';

$client = new Google_Client();
$client->setUseObjects(true);
$calendarApi = new Google_CalendarService($client);
$client->setApplicationName("DutyManager");
$client->setClientId('154411771178-t9f4undfn5i0s1j6iekarmbof01pbp7g.apps.googleusercontent.com');
$client->setClientSecret('tuPSrR5t7NnJwy7D-yc-Ynv0');
$client->setScopes('https://www.google.com/calendar/feeds');
$client->setRedirectUri('http://dutymanager.funsite.cz/check');
//$client->setRedirectUri('http://localhost/duty/check');

if (isset($_SESSION['access_token']))
    $client->setAccessToken($_SESSION['access_token']);

set_time_limit( 0 );


return $container;
