<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '3ef45cd622125e9a33997a2dd5e57eb4' => $vendorDir . '/nette/nette/Nette/common/shortcuts.php',
);
